# Welcome to Jekyll!

# Site settings
title: Antonio Ossa
email: aaossa@uc.cl
description: > # this means to ignore newlines until "baseurl:"
  Página web personal de Antonio Ossa Guerra (aaossa@uc.cl)
twitter_username: aaossa
github_username:  aaossa

# Build settings
highlighter: pygments
markdown: kramdown
port: 5000

# More settings
encoding: utf-8
permalink: /blog/:title
timezone: America/Santiago