# Welcome to Jekyll!

# Site settings
title: Antonio Ossa
email: aaossa@uc.cl
description: > # this means to ignore newlines until next setting
  Página web personal de Antonio Ossa Guerra
username: aaossa

# Build settings
highlighter: rogue
markdown: kramdown
port: 5000

# More settings
encoding: utf-8
permalink: /blog/:title
timezone: America/Santiago