# Main settings
title: Antonio Ossa
email: aaossa@uc.cl
description: Página personal de Antonio Ossa Guerra
description_en: Antonio Ossa's personal webpage

# Author
author: Antonio Ossa
author_codepen: http://codepen.io/aaossa
author_email: aaossa@uc.cl
author_facebook: https://www.facebook.com/aaossa
author_github: https://github.com/aaossa
author_linkedin: https://www.linkedin.com/in/aaossa
author_telegram: https://telegram.me/aaossa
author_twitter: https://twitter.com/aaossa
avatar: https://avatars3.githubusercontent.com/u/10425834

# Build settings
highlighter: rouge
markdown: kramdown
sass:
  style: :compressed

# Extra settings
encoding: utf-8
permalink: /blog/:title
lang: es
timezone: America/Santiago
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md